services:
  postgres:
    image: postgres:15
    container_name: ftjj_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ftjj
      POSTGRES_PASSWORD: ftjj_secret_2025
      POSTGRES_DB: ftjj_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
