import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import rateLimit from 'express-rate-limit';
import routes from './routes/index.js';
import path from 'path';
import { notFound, errorHandler } from './middlewares/error.middleware.js';

const app = express();
app.use(helmet());
app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5173', credentials: true }));
app.use(express.json({ limit: '10mb' }));
app.use('/uploads', express.static(path.join(process.cwd(), 'src', 'uploads')));
app.use(morgan('dev'));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, max: 300 }));
app.get('/api/health', (req, res) => res.json({ status: 'ok', project: 'FTJJ MERN Platform' }));
app.use('/api', routes);
app.use(notFound);
app.use(errorHandler);
export default app;
