import { Router } from 'express';
import authRoutes from './auth.routes.js';
import { resourceRoutes } from './resource.routes.js';
import { crudController } from '../controllers/crud.controller.js';
import { stats } from '../controllers/dashboard.controller.js';
import { protect, allowRoles } from '../middlewares/auth.middleware.js';
import workflowRoutes from './workflow.routes.js';
import importRoutes from './import.routes.js';
import License from '../models/License.js';
import Fight from '../models/Fight.js';
import AuditLog from '../models/AuditLog.js';
import Club from '../models/Club.js';
import Athlete from '../models/Athlete.js';
import Coach from '../models/Coach.js';
import Referee from '../models/Referee.js';
import Technician from '../models/Technician.js';
import Competition from '../models/Competition.js';
import Document from '../models/Document.js';
import Payment from '../models/Payment.js';
import contentRoutes from './content.routes.js';
import publicRoutes from './public.routes.js';
import settingsRoutes from './settings.routes.js';
import exportRoutes from './export.routes.js';
import notificationRoutes from './notifications.routes.js';
import uploadRoutes from './uploads.routes.js';
import liveRoutes from './live.routes.js';
import profileRoutes from './profile.routes.js';
import cmsRoutes from './cms.routes.js';
import mediaRoutes from './media.routes.js';
import eventsRoutes from './events.routes.js';
import newsRoutes from './news.routes.js';
import competitionWorkflowRoutes from './competitionWorkflow.routes.js';
import scoringRoutes from './scoring.routes.js';
import federalIntegrationRoutes from './federalIntegration.routes.js';
import Event from '../models/Event.js';
import News from '../models/News.js';
import MediaAsset from '../models/MediaAsset.js';
import Category from '../models/Category.js';
import Bracket from '../models/Bracket.js';
import CompetitionRegistration from '../models/CompetitionRegistration.js';
import Ranking from '../models/Ranking.js';
import ScoringSession from '../models/ScoringSession.js';
import ScoringActionLog from '../models/ScoringActionLog.js';
import ScoringSettings from '../models/ScoringSettings.js';


const router = Router();
router.use('/auth', authRoutes);
router.use('/public', publicRoutes);
router.use('/profile', profileRoutes);
router.use('/cms', cmsRoutes);
router.use('/media', mediaRoutes);
router.use('/events', eventsRoutes);
router.use('/news', newsRoutes);
router.use('/competitions', competitionWorkflowRoutes);
router.use('/scoring', scoringRoutes);
router.use('/federal-integration', federalIntegrationRoutes);

router.use('/settings', settingsRoutes);
router.use('/exports', exportRoutes);
router.use('/notifications', notificationRoutes);
router.use('/uploads', uploadRoutes);
router.use('/live', liveRoutes);
router.get('/dashboard/stats', protect, allowRoles('SUPER_ADMIN','FEDERATION_ADMIN','COMPETITION_MANAGER'), stats);
router.use('/import', importRoutes);
router.use('/workflow', workflowRoutes);
router.use('/content', contentRoutes);
router.use('/clubs', resourceRoutes(crudController(Club), true));
router.use('/athletes', resourceRoutes(crudController(Athlete, { populate: 'club', search: true })));
router.use('/coaches', resourceRoutes(crudController(Coach, { populate: 'club' })));
router.use('/referees', resourceRoutes(crudController(Referee)));
router.use('/technicians', resourceRoutes(crudController(Technician, { populate: 'club' })));
router.use('/competitions', resourceRoutes(crudController(Competition)));
router.use('/documents', resourceRoutes(crudController(Document), false));
router.use('/payments', resourceRoutes(crudController(Payment), false));
router.use('/licenses', resourceRoutes(crudController(License), false));
router.use('/fights', resourceRoutes(crudController(Fight, { populate: 'competition redAthlete blueAthlete winner' }), false));
router.use('/audit-logs', resourceRoutes(crudController(AuditLog, { populate: 'actor' }), true));

router.use('/categories', resourceRoutes(crudController(Category), false));
router.use('/brackets', resourceRoutes(crudController(Bracket, { populate: 'categoryId seeds.athlete' }), false));
router.use('/registrations', resourceRoutes(crudController(CompetitionRegistration, { populate: 'competitionId clubId athleteId submittedBy' }), false));
router.use('/rankings-admin', resourceRoutes(crudController(Ranking, { populate: 'athlete club' }), false));
router.use('/scoring-sessions-admin', resourceRoutes(crudController(ScoringSession, { populate: 'fight competition' }), false));
router.use('/scoring-action-logs', resourceRoutes(crudController(ScoringActionLog, { populate: 'actorUserId fightId scoringSessionId' }), true));
router.use('/scoring-settings', resourceRoutes(crudController(ScoringSettings), false));
router.use('/events-admin', resourceRoutes(crudController(Event), false));
router.use('/news-admin', resourceRoutes(crudController(News), false));
router.use('/media-admin', resourceRoutes(crudController(MediaAsset), false));

export default router;
