import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import AdminLayout from '../../components/layout/AdminLayout';
import api from '../../services/api';

export default function ScoringControl() {
  const { sessionId } = useParams();
  const [session, setSession] = useState(null);
  const [message, setMessage] = useState('');
  async function load() { const { data } = await api.get(`/scoring/sessions/${sessionId}`); setSession(data); }
  useEffect(()=>{ load(); }, [sessionId]);
  async function patch(path, payload={}) { try { const { data } = await api.patch(path, payload); setSession(data); } catch(e) { setMessage(e.response?.data?.message || 'Action impossible'); } }
  if (!session) return <AdminLayout><div className="notice">Chargement scoring...</div></AdminLayout>;
  const fight = session.fight || {};
  return <AdminLayout><div className="score-control"><h1>{fight.category || session.discipline}</h1>{message && <div className="notice">{message}</div>}<div className="scoreboard"><div className="red"><h2>{fight.redAthlete?.firstName} {fight.redAthlete?.lastName}</h2><strong>{session.red?.score || 0}</strong><span>Av {session.red?.advantages || 0} / Pen {session.red?.penalties || 0}</span></div><div className="timer"><strong>{Math.floor((session.remainingSeconds || 0)/60)}:{String((session.remainingSeconds || 0)%60).padStart(2,'0')}</strong><span>{session.timerState}</span></div><div className="blue"><h2>{fight.blueAthlete?.firstName} {fight.blueAthlete?.lastName}</h2><strong>{session.blue?.score || 0}</strong><span>Av {session.blue?.advantages || 0} / Pen {session.blue?.penalties || 0}</span></div></div><div className="table-row-actions"><button onClick={()=>patch(`/scoring/sessions/${sessionId}/start`)}>Start</button><button onClick={()=>patch(`/scoring/sessions/${sessionId}/pause`)}>Pause</button><button onClick={()=>patch(`/scoring/sessions/${sessionId}/resume`)}>Resume</button><button onClick={()=>patch(`/scoring/sessions/${sessionId}/doctor-time`)}>Doctor Time</button><button onClick={()=>patch(`/scoring/sessions/${sessionId}/waiting-time`)}>Waiting Time</button><button onClick={()=>patch(`/scoring/sessions/${sessionId}/undo`)}>Undo</button></div><div className="grid two"><section className="panel"><h2>Rouge</h2><button onClick={()=>patch(`/scoring/sessions/${sessionId}/action`, { side:'red', type:'points', value:2 })}>+2 points</button><button onClick={()=>patch(`/scoring/sessions/${sessionId}/action`, { side:'red', type:'advantage', value:1 })}>+1 avantage</button><button onClick={()=>patch(`/scoring/sessions/${sessionId}/action`, { side:'red', type:'penalty', value:1 })}>Penalty</button><button onClick={()=>patch(`/scoring/sessions/${sessionId}/finish`, { winnerSide:'red', winMethod:'points' })}>Rouge gagne</button></section><section className="panel"><h2>Bleu</h2><button onClick={()=>patch(`/scoring/sessions/${sessionId}/action`, { side:'blue', type:'points', value:2 })}>+2 points</button><button onClick={()=>patch(`/scoring/sessions/${sessionId}/action`, { side:'blue', type:'advantage', value:1 })}>+1 avantage</button><button onClick={()=>patch(`/scoring/sessions/${sessionId}/action`, { side:'blue', type:'penalty', value:1 })}>Penalty</button><button onClick={()=>patch(`/scoring/sessions/${sessionId}/finish`, { winnerSide:'blue', winMethod:'points' })}>Bleu gagne</button></section></div><button className="primary" onClick={()=>patch(`/scoring/sessions/${sessionId}/validate`)}>Validate result</button></div></AdminLayout>;
}
